### ISSUE TITLE
Linux 1.1.1 release zip does not contain the bluehound binary 

### ISSUE THREAD

**Issue by Gunbird** [zeronetworks/BlueHound#13]
The zip file for linux release 1.1.1 does not contain the bluehound binary.

The top directory is also missing.

Regards

**Comment by dekelpaz** [comment]
fixed

**Comment by Gunbird** [comment]
This is less critical but the top directory is still missing in the archive.
